version: '3'

services:
  api-server:
    build: .
    ports:
      - "5000:5000"
    depends_on: 
      - postgres
      - redis
    networks: 
      - network
    environment: 
      DB_HOST: postgres
      REDIS_HOST: redis

  postgres:
    image: postgres:12.4
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    networks: 
      - network
    volumes: 
      - postgres-data:/data/pg
      - ./migrations/:/docker-entrypoint-initdb.d/

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment: 
      REDIS_URL: redis://redis_db:6379
    networks: 
      - network


networks: 
  network:
    driver: bridge


volumes: 
  postgres-data: